[tool.poetry]
name = "model_settlement"
version = "0.1.7"
description = "Model Settlement"
authors = ["Teja <teja@spraoi.ai>"]
maintainers = [
    "TBD <TBD@spraoi.ai>",
]
license = "MIT"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: CPython",
]


[tool.poetry.dependencies]
python = "~3.8"
boto3 = "*"
pandas = "1.*"
numpy = "1.*"
joblib = "*"
tensorflow = "2.*"
xgboost = "1.*"
scikit-learn = "*"  # needed though it's not obvious in the code
fsspec = "*" # needed by pandas

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
