[tool.poetry]
name = "model_settlement"
version = "0.1.9"
description = "Model Settlement"
authors = ["Teja <teja@spraoi.ai>"]
maintainers = [
    "TBD <TBD@spraoi.ai>",
]
license = "Proprietry"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: CPython",
]


[tool.poetry.dependencies]
python = "~3.8"
boto3 = "1.*"
botocore = "1.*"
pandas = "*"
numpy = "*"
joblib = "*"
tensorflow = "2.7.*"
xgboost = "*"
scikit-learn = "*"  # needed though it's not obvious in the code
s3fs = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
