default_language_version:
  python: python3.9
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: debug-statements
      -   id: check-yaml
      -   id: check-json
      -   id: check-merge-conflict
      -   id: pretty-format-json
          args: ['--autofix']
      -   id: check-added-large-files
      -   id: debug-statements
  -   repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
      -   id: isort
          args: [ "--profile", "black", "--filter-files" ]
  -   repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
      -   id: black