[tool.poetry]
name = "model_ffm"
version = "0.1.7"
description = "Model FFM"
authors = ["Teja <teja@spraoi.ai>"]
maintainers = [
    "TBD <TBD@spraoi.ai>",
]
license = "MIT"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: CPython",
]
packages = [
    { include = "model_ffm" }
]
include = ["model_ffm/data/*"]

[tool.poetry.dependencies]
python = "^3.8"
tensorflow = "~2.3"
pandas = "~1.2"
numpy = "~1.18"
inflection = "~0.5"
joblib = "~1.0"
tokenizers = "~0.10"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
