[tool.poetry]
name = "model_ffm"
version = "0.2.4"
description = "Model FFM"
authors = ["Tariq <tariqmohamed@fineos.com>"]
maintainers = [
    "Tariq <tariqmohamed@fineos.com>",
]
license = "Proprietary"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: CPython",
]
packages = [
    { include = "model_ffm" }
]
include = ["model_ffm/data/*"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "~1.2"
onnxruntime = "~1.11"
numpy = "~1.22"
inflection = "~0.5"
joblib = "~1.0"
tokenizers = "~0.10"
werkzeug = "0.*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
